name: Update CSV every 6 hours

on:
  schedule:
    # هر 6 ساعت یکبار اجرا می‌شود
    - cron: "0 */6 * * *"
  workflow_dispatch: # امکان اجرای دستی

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run update script
        run: |
          python update_csv.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add blackouts.csv
          git commit -m "Auto-update blackouts.csv"
          git push
        env:
          # دسترسی به توکن گیت (برای push)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
